#!/usr/bin/env python3

"""
Module to create a PDF report.
"""

from jinja2 import Environment, FileSystemLoader
import os.path
import time
from xhtml2pdf import pisa


def write_header(rep_name="SAVI Analytics Report", title="SAVI",
                 alt_name="Logo SAVI"):
    """ Returns HTML file with header.

    rep_name -- string, name of report, default: SAVI Analytics Report
    title -- string, title of report, default: SAVI
    figure -- string, logo of SAVI, default: #have to find out how
    """
    env = Environment(loader=FileSystemLoader('C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML')) # to local folder
    template = env.get_template("header.html")
    fig_path = "C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML\\Logo.png" #Should be changed
    text = "This report was generated by SAVI Analytics on {}.".format(time.strftime("%B %d, %Y"))
    variables = {"title" : title,
                 "report_name" : rep_name,
                 "figure" : fig_path,
                 "alt_name" : alt_name,
                 "width" : "300",
                 "height" : "250",
                 "align" : "right",
                 "date" : "{}".format(time.strftime("%Y%m%d")),
                 "text" : text
                }
    html_out = template.render(variables)
    return(html_out)

    
def write_footer():
    """ Returns HTML file with footer.
    
    """
    env = Environment(loader=FileSystemLoader('C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML')) # to local folder
    template = env.get_template("header.html")
    variables = {"year" : "{}".format(time.strftime("%Y"))
                }
    html_out = template.render(variables)
    return(html_out)

    
def write_statistic(stat_meth, fig, alt_name):
    """ Returns HTML file with statistcal output.

    stat_meth -- string, specifies stastical analysis
    fig -- string ###SHOULD BE CHANGED!
    alt_name -- string, name if image cannot be displayed
    fig -- integer, indicates number of figure
    txt -- string, text describing figure
    """
    env = Environment(loader=FileSystemLoader('C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML')) # to local folder
    template = env.get_template("stat_meth.html")
    variables = {"statistical_method" : stat_meth,
                 "figure" : fig,
                 "alt_name" : alt_name,
                 "width" : "400",
                 "height" : "400",
                 # "figure" : fig,
                 # "text" : txt
                 }
    html_out = template.render(variables)
    return(html_out)


def make_pdf(html_temp, title="SAVI Analytics Report"):
    """ Creates a PDF from a HTML template with date of today.

    html_temp -- html, template
    title -- string, title of report, default: SAVI Analytics Report 
    """   
    report_name = "{} {}.pdf".format(title, time.strftime("%Y%m%d"))
    env = Environment(loader=FileSystemLoader('C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML')) # to local folder
    #env = Environment(loader=FileSystemLoader('.')) #current directory
    if os.path.isfile(report_name):
        os.remove(report_name) #figure out better solution
    ## this would be better: 
    #os.path.exists(file_path)
    ## have to know file path
    
    # write end of file to template :
    temp_EOF = env.get_template("EOF.html")
    html_temp += temp_EOF.render()
    #print(html_file)

    # generate PDF :
    report = open(report_name, "w+b")
    pisa_status = pisa.CreatePDF(html_temp, dest=report)
    report.close()
    print(pisa_status.err) #True on succes, False on error
    os.startfile(report_name)


##def write_to_template(var1, var2, var3)
##    """ Returns HTML file of header, statistical method with figure
##
##    var1 -- string, variable 1
##    var2 -- string, variable 2
##    var3 -- string, variable 3
##    """
##    #use case ... if ...


if __name__ == '__main__':
   
    # get template :
    env = Environment(loader=FileSystemLoader('C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML')) # to local folder
    #env = Environment(loader=FileSystemLoader('.')) #current directory
    # write start of file to template
    html_file = write_header()
    # write body to template
    html_file += write_statistic("Stastical Method",
                                 "C:\\Users\\marij\\Dropbox\\Wageningen\\ACT\\Toolkit_Work\\Toolkit\\HTML\\test_fig.png",
                                 "Marijke")
    
    make_pdf(html_file)
    

    
